local config = require("tamagotchi.config")
local assert = require("luassert")
local kitty_sprites = require("tamagotchi.sprites.kitty")

describe("window_toggle_keybind configuration", function()
    it("should use default config when no user config is provided", function()
        config.setup()
        assert.are.equal("<leader>tg", config.values.window_toggle_keybind)
    end)

    it("should override default config with user values", function()
        config.setup({ window_toggle_keybind = "<leader>xx" })
        assert.are.equal("<leader>xx", config.values.window_toggle_keybind)
    end)
end)

describe("configuration with multiple pets", function()
    it("should have a default list of pets", function()
        config.setup()
        assert.is_table(config.values.pets)
        assert.is_true(#config.values.pets >= 1)
        local first_pet = config.values.pets[1]
        assert.are.equal("Ilya", first_pet.name)
        assert.is_table(first_pet.sprites)
    end)
end)
